# Generated by Django 6.0.3 on 2026-06-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='roll_number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='rating',
            name='room_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
